image:
  file: .gitpod.Dockerfile
tasks:
  - name: setup
    before: |
       clear && echo "Hello World !"

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

